logging:
  level:
    org:
      springframework:
        web: INFO
---
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/brumfinance_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  
  jpa:
    database: MYSQL
    show-sql: true
    
    properties:
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
     
    
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
       
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: true
  
  flyway:
    enabled: true
     
       
